### ISSUE TITLE
Add plugin to Awesome Textpattern

### ISSUE THREAD

**Issue by drmonkeyninja** [NicolasGraph/oui_dailymotion#1]
If this plugin is stable feel free to add it to the Videos section of [Awesome Textpattern](https://github.com/drmonkeyninja/awesome-textpattern).

**Comment by NicolasGraph** [comment]
Hi, in fact there are still few options missing.
Moreover I would like to contact you before to release it, as the code is a fork from your video plugins.
If you agree, I’ll tell you when it will be finished and you can change it to arc_dailymotion. Like that it will be updated at the same time in the future and it will be more 'logical' to use with arc_youtube and arc_vimeo…
I also thought that the three plugins could become one like arc_video, but that is another story…

**Comment by NicolasGraph** [comment]
I simplified few code lines and add last parameters. I can't test the api parameter but other attributes seem to work well. Do you want oui_dailymotion to become arc_dailymotion or should I add it directly in the Awesome Textpattern listing?

**Comment by drmonkeyninja** [comment]
Keep it as oui_dailymotion as it's you that has put all the leg work in, so you deserve the credit. :smiley: I'll add a reference to arc_youtube and arc_vimeo that this plugin exists when I next update the plugins.

Just make a pull request to add oui_dailymotion to Awesome Textpattern.

**Comment by drmonkeyninja** [comment]
Also, in regards to arc_video I've actually already started work on this plugin. The plan is for it to support multiple players, but will probably be less customisable than using the individual plugins. Your comment has persuaded me to get back to developing it. I already have a very similar plugin for the CakePHP framework (https://github.com/drmonkeyninja/cakephp-video-helper).

**Comment by NicolasGraph** [comment]
Pull request sent. 
arc_video could be really nice; I understand it could be less custumisable but honestly, in oui_dailymotion for exemple, there are some parameters nobody will probably use anyway…

**Comment by drmonkeyninja** [comment]
Thanks.
